name: ozonteck_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  image_cropper: ^5.0.0

  # Firebase
  firebase_core: ^2.31.1
  cloud_firestore: ^4.17.4
  firebase_auth: ^4.19.6

  # Bloc
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  bloc: ^8.1.4

  # Custom Repository
  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
