name: ozonteck_mobile
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0

  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^2.9.0
  firebase_auth: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
